version: "3.7"
services:
  jupyterlab:
    build: ./contents
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - /home/kdm/Desctop/masterResurch/GaussianProcessRegression:/home/jovyan/work
    command: start.sh jupyter lab --NotebookApp.token=''
